### ISSUE TITLE
Bitcoin PSBT GenerateSignedBuyingTx Error: Invalid Schnorr signature

### ISSUE THREAD

**Issue by TsengMJ** [okx/go-wallet-sdk#16]
Got the following error return from RPC node after sending generated singed buying tx:

failed to parse tx hash, sendrawtransaction RPC error: {"code":-26,"message":"non-mandatory-script-verify-flag (Invalid Schnorr signature)"}: max hash string length is 64 bytes

What I implemented different between psbt_tx_test.go is that I can not get the real seller's input (the privatekey part), so replaced the SellerSignatureIndex input to a fake one (also it should be replaced by the actual one from seller psbt). And it works for finalize and get raw transaction but get "Invalid Schnorr signature" error~

Anything I missed or misused？

**Comment by yanminmin** [comment]
hi,could you provide your tx data and your public key?
Do not provide your private key！

**Comment by TsengMJ** [comment]
Hi, thank u for response~ I found out how to solve the issue by setting the "SellerSignatureIndex" of TxInput exact the same as seller's input (TxId, VOut, Amout, Address, expect private key). Did not know these params will really affect the signing result (cause there is a input replacement in GenerateSignedBuyingTx function)
