### ISSUE TITLE
How do I get the appropriate feerate dynamically

### ISSUE THREAD

**Issue by york0xiong** [okx/go-wallet-sdk#27]
inscribe_test, the estimatesmartfee command can get feerate,  Do it need to be converted ?  

request := &InscriptionRequest{
		CommitTxPrevOutputList: commitTxPrevOutputList,
		CommitFeeRate:          2,
		RevealFeeRate:           2,
		RevealOutValue:         546,
		InscriptionDataList:    inscriptionDataList,
		ChangeAddress:          "tb1pklh8lqax5l7m2ycypptv2emc4gata2dy28svnwcp9u32wlkenvsspcvhsr",
	}

**Comment by yanminmin** [comment]
You can find the appropriate api to calculate dynamic fees
