### ISSUE TITLE
TestReveal builder args question

### ISSUE THREAD

**Issue by Howard0401** [okx/go-wallet-sdk#28]
Hi, I found in the TestReveal
The privatekey: 1790962db820729606cd7b255ace1ac5ebb129ac8e9b2d8534d022194ab25b37
And turn the privatekey into address is not same as following "tb1pmwus5lpxnnet6wcyqtevls07y7u8h5wun7q7p9jglk707y2czfnsdlqqjw"

Is there any relationship between the privatekey tb1pmwus5lpxnnet6wcyqtevls07y7u8h5wun7q7p9jglk707y2czfnsdlqqjw
And address argument? 
tb1pmwus5lpxnnet6wcyqtevls07y7u8h5wun7q7p9jglk707y2czfnsdlqqjw
```
builder.AddInput("9f9ff5acc7b3966ccfc6acc77027209d62aab34e563a09180c58ef7296fca74b",
		1,
		"1790962db820729606cd7b255ace1ac5ebb129ac8e9b2d8534d022194ab25b37",
                  // not same as privatekey made by 1790962db820729606cd7b255ace1ac5ebb129ac8e9b2d8534d022194ab25b37
		"tb1pmwus5lpxnnet6wcyqtevls07y7u8h5wun7q7p9jglk707y2czfnsdlqqjw", 
		"1600",
		inscription,
	)
```

**Comment by yanminmin** [comment]
The two are not related, but they can be complementary.
