### ISSUE TITLE
BItcoin Brc20 sendrawtransaction Error: -26 non-mandatory-script-verify-flag (Witness program hash mismatch)

### ISSUE THREAD

**Issue by yuhai-yang** [okx/go-wallet-sdk#32]
I'm trying using this sdk to transfer inscriptions. When I try to use bitcoin-core cli to broadcast the generated tx data, an error is returned.  

Net: Bitcoin Test Net 

MyTxData:  
01000000000101dff84afd95cd2b7e79b6296d40d758a3db9852374ff21c4677718e9d8cc5323b0100000000ffffffff022202000000000000225120977afe0a8654c13bdf7a33383d643c8f47809edb27f11d2520e697b3a8b5b902d586070000000000225120cac2695acccce6e39677275888d8e3f30d06ffcc983c6c044b5b359f8ffc847403405b6e9dd0a1110b74e05deb2c66861c379460f049c784f886bfedb82353bfef237548dd97c1ee3afb32134f95e250cc8e1250351641dabc48224491de80dad4267d20af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f903ac0063036f7264010118746578742f706c61696e3b636861727365743d7574662d3800377b2270223a226272632d3230222c226f70223a227472616e73666572222c227469636b223a2273617473222c22616d74223a223130227d6821c1af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f90300000000

Decode Transaction 

```
{
    "addresses": [
        "tb1petpxjkkvennw89nhyavg3k8r7vxsdl7vnq7xcpzttv6elrlus36q2s72kp",
        "tb1pjaa0uz5x2nqnhhm6xvur6epu3arcp8kmylc36ffqu6tm8294hypq4dt2rl"
    ],
    "block_height": -1,
    "block_index": -1,
    "confirmations": 0,
    "double_spend": false,
    "fees": 369,
    "hash": "b49889343ce43f7958059ab3718649784b4741ac441d42933b48a75530304d61",
    "inputs": [
        {
            "addresses": [
                "tb1petpxjkkvennw89nhyavg3k8r7vxsdl7vnq7xcpzttv6elrlus36q2s72kp"
            ],
            "age": 2576585,
            "output_index": 1,
            "output_value": 494184,
            "prev_hash": "3b32c58c9d8e7177461cf24f375298dba358d7406d29b6797e2bcd95fd4af8df",
            "script_type": "pay-to-taproot",
            "sequence": 4294967295,
            "witness": [
                "5b6e9dd0a1110b74e05deb2c66861c379460f049c784f886bfedb82353bfef237548dd97c1ee3afb32134f95e250cc8e1250351641dabc48224491de80dad426",
                "20af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f903ac0063036f7264010118746578742f706c61696e3b636861727365743d7574662d3800377b2270223a226272632d3230222c226f70223a227472616e73666572222c227469636b223a2273617473222c22616d74223a223130227d68",
                "c1af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f903"
            ]
        }
    ],
    "outputs": [
        {
            "addresses": [
                "tb1pjaa0uz5x2nqnhhm6xvur6epu3arcp8kmylc36ffqu6tm8294hypq4dt2rl"
            ],
            "script": "5120977afe0a8654c13bdf7a33383d643c8f47809edb27f11d2520e697b3a8b5b902",
            "script_type": "pay-to-taproot",
            "value": 546
        },
        {
            "addresses": [
                "tb1petpxjkkvennw89nhyavg3k8r7vxsdl7vnq7xcpzttv6elrlus36q2s72kp"
            ],
            "script": "5120cac2695acccce6e39677275888d8e3f30d06ffcc983c6c044b5b359f8ffc8474",
            "script_type": "pay-to-taproot",
            "value": 493269
        }
    ],
    "preference": "low",
    "received": "2024-02-05T08:04:54.373936891Z",
    "relayed_by": "3.236.147.57",
    "size": 365,
    "total": 493815,
    "ver": 1,
    "vin_sz": 1,
    "vout_sz": 2,
    "vsize": 194
}
```

Error :
non-mandatory-script-verify-flag (Witness program hash mismatch) (code -26)

I hope I can get help to resolve this error :)

**Comment by yuhai-yang** [comment]
> 01000000000101dff84afd95cd2b7e79b6296d40d758a3db9852374ff21c4677718e9d8cc5323b0100000000ffffffff022202000000000000225120977afe0a8654c13bdf7a33383d643c8f47809edb27f11d2520e697b3a8b5b902d586070000000000225120cac2695acccce6e39677275888d8e3f30d06ffcc983c6c044b5b359f8ffc847403405b6e9dd0a1110b74e05deb2c66861c379460f049c784f886bfedb82353bfef237548dd97c1ee3afb32134f95e250cc8e1250351641dabc48224491de80dad4267d20af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f903ac0063036f7264010118746578742f706c61696e3b636861727365743d7574662d3800377b2270223a226272632d3230222c226f70223a227472616e73666572222c227469636b223a2273617473222c22616d74223a223130227d6821c1af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f90300000000 This does not contain a signature
This raw transaction is generated using this sdk

**Comment by Levin932** [comment]
how to  to resolve this error :????? who know

**Comment by yanminmin** [comment]
Can you provide a demo? Let's see if we can replicate that and how we can fix it.

**Comment by yanminmin** [comment]
None of our colleagues  using the sdk are experiencing the same issues. You may need to provide a demo for verification.

**Comment by arvin-lau** [comment]
这个问题解决了吗?我遇到了同样的报错

**Comment by arvin-lau** [comment]
> issues

您好,你知道如何修复这个问题吗?我在主网使用sdk构建交易后遇到了同样的问题

**Comment by arvin-lau** [comment]
> None of our colleagues using the sdk are experiencing the same issues. You may need to provide a demo for verification.↳

您好,你知道如何修复这个问题吗?我在主网使用sdk构建交易后遇到了同样的问题

**Comment by arvin-lau** [comment]
> None of our colleagues using the sdk are experiencing the same issues. You may need to provide a demo for verification.↳

`package main

import (
	"fmt"
	"github.com/btcsuite/btcd/btcutil"
	"github.com/btcsuite/btcd/chaincfg"
	"github.com/okx/go-wallet-sdk/coins/bitcoin/brc20"
	"github.com/rs/zerolog/log"
)

func main() {

	builder := brc20.NewTxBuildV1(&chaincfg.MainNetParams)

	contentType := "text/plain;charset=utf-8"
	body := []byte(fmt.Sprintf(`{"p":"brc-20","op":"%s","tick":"%s","amt":"%s"}`, "transfer", "sats", "1"))

	inscription := brc20.NewInscription(contentType, body)

	privatekeyStr := ""
	privateKeyWif, err := btcutil.DecodeWIF(privatekeyStr)
	if err != nil {
		log.Error().Msg("DecodeWIF err: " + err.Error())
		return
	}
	builder.AddInput("434876ec149a94971a630ebb3a70ffa4869ab1a992f1500b4b035a21cbbe7c80",
		1,
		privateKeyWif.PrivKey.Key.String(),
		"bc1pg3zt4vv6a8hg7y935xjw26rvyc879wcwxj5fxzyd8m2mvwqpleqszlwqm7",
		"81024",
		inscription,
	)
	builder.AddOutput("bc1pg3zt4vv6a8hg7y935xjw26rvyc879wcwxj5fxzyd8m2mvwqpleqszlwqm7", "546")
	builder.AddOutput("bc1pg3zt4vv6a8hg7y935xjw26rvyc879wcwxj5fxzyd8m2mvwqpleqszlwqm7", "77000")
	tx, err := builder.Build()
	if err != nil {
		log.Error().Msg("Build err: " + err.Error())
		return
	}
	fmt.Println("tx: ", tx)
}`


err: {
    "result": null,
    "error": {
        "code": -26,
        "message": "mandatory-script-verify-flag-failed (Witness program hash mismatch)"
    },
    "id": "getblock.io"
}

**Comment by arvin-lau** [comment]
> 01000000000101dff84afd95cd2b7e79b6296d40d758a3db9852374ff21c4677718e9d8cc5323b0100000000ffffffff022202000000000000225120977afe0a8654c13bdf7a33383d643c8f47809edb27f11d2520e697b3a8b5b902d586070000000000225120cac2695acccce6e39677275888d8e3f30d06ffcc983c6c044b5b359f8ffc847403405b6e9dd0a1110b74e05deb2c66861c379460f049c784f886bfedb82353bfef237548dd97c1ee3afb32134f95e250cc8e1250351641dabc48224491de80dad4267d20af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f903ac0063036f7264010118746578742f706c61696e3b636861727365743d7574662d3800377b2270223a226272632d3230222c226f70223a227472616e73666572222c227469636b223a2273617473222c22616d74223a223130227d6821c1af2d240e6e2686473825bc9f455f2ecfa31da07d7129382693b94ca6f3d2f90300000000

请问你解决这个问题了吗?
