### ISSUE TITLE
Inscribing BRC-20 Tokens in JavaScript

### ISSUE THREAD

**Issue by ShubhamRev** [okx/go-wallet-sdk#41]
I am currently working on a project that involves integrating BRC-20 tokens into our platform using JavaScript. I am seeking assistance on how to inscribe BRC-20 tokens in JavaScript.

Could you please provide guidance or resources on how to inscribe BRC-20 tokens using JavaScript? Any code examples or documentation would be greatly appreciated.

Thank you for your time and support. I look forward to your response.

**Comment by kaijiel24** [comment]
You can take a look at our [js-wallet-sdk](https://github.com/okx/js-wallet-sdk/tree/main), specifically this [brc20 test file](https://github.com/okx/js-wallet-sdk/blob/main/packages/coin-bitcoin/tests/brc20.test.ts ) for an example.
