### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by parham2013** [okx/go-wallet-sdk#45]
![image](https://github.com/okx/go-wallet-sdk/assets/74326920/ea2721d0-efc9-4c64-b51b-a37ee5d54aa5)

![image](https://github.com/okx/go-wallet-sdk/assets/74326920/8bec211b-68b6-4d5c-8ee8-f38f82ce3562)

eth.go example doesn't work

**Comment by zychappy** [comment]
go mod tidy

**Comment by parham2013** [comment]
> go mod tidy

That's the first thing i did

**Comment by zychappy** [comment]
> > go mod tidy
> 
> That's the first thing i did

1 make sure the project's path is in the GOPATH;
2 execute go mod tidy should be in the package path,such as  ~/go/src/go-wallet-sdk/example :go mod tidy
3 something package needs to execute manually like go get github.com/okx/go-wallet-sdk/crypto/bip32@v0.0.2
it works in my computer. if you try to use these functions in other project,make sure use the right quote or alias.

<img width="856" alt="image" src="https://github.com/okx/go-wallet-sdk/assets/9582529/87bbd67b-f0c4-485d-afff-3af220aeb3d5">
<img width="1551" alt="image" src="https://github.com/okx/go-wallet-sdk/assets/9582529/8d810dc9-3e5f-4f59-b672-bf3be4f5ccc3">

**Comment by yanminmin** [comment]
> > > go mod tidy
> > 
> > 
> > That's the first thing i did
> 
> 1 make sure the project's path is in the GOPATH; 2 execute go mod tidy should be in the package path,such as ~/go/src/go-wallet-sdk/example :go mod tidy 3 something package needs to execute manually like go get github.com/okx/go-wallet-sdk/crypto/bip32@v0.0.2 it works in my computer. if you try to use these functions in other project,make sure use the right quote or alias.
> 
> <img alt="image" width="856" src="https://private-user-images.githubusercontent.com/9582529/331169349-87bbd67b-f0c4-485d-afff-3af220aeb3d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzA3NjEsIm5iZiI6MTcxNjM3MDQ2MSwicGF0aCI6Ii85NTgyNTI5LzMzMTE2OTM0OS04N2JiZDY3Yi1mMGM0LTQ4NWQtYWZmZi0zYWYyMjBhZWIzZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDkzNDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTAwNTIzNWU1NTE5MDE5MTg1MDYyNGNjYTU5OWM5NTA2Nzk1YzgzZGYzMDI2YThkY2M3OGRjNDcxYjllMzM5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9Xwgh0EI-SrSZxA_lVbuCJFr9DYHkUoxZK8AV4NivzY"> <img alt="image" width="1551" src="https://private-user-images.githubusercontent.com/9582529/331169661-8d810dc9-3e5f-4f59-b672-bf3be4f5ccc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzA3NjEsIm5iZiI6MTcxNjM3MDQ2MSwicGF0aCI6Ii85NTgyNTI5LzMzMTE2OTY2MS04ZDgxMGRjOS0zZTVmLTRmNTktYjY3Mi1iZjNiZTRmNWNjYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDkzNDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVlZjBmMTYyN2M4YzMyYjZiYjBmMWJjNGE5NzQyNmYwZTY5MzllNTBmYjA2YzljY2Y2YTg5M2Q2NDFmOTEwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MeFoWsKu0sD38CagEwVLvaw4-nE7n26H4I_EaUL_z0g">

great.thanks.
