### ISSUE TITLE
cant find crypto.ra

### ISSUE THREAD

**Issue by babt123654** [okx/go-wallet-sdk#48]
C:\Users\Administrator\go\go1.21.10\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lzks-crypto: No such file or directory
collect2.exe: error: ld returned 1 exit status

describe：but F:\Hy\go-wallet-sdk\coins\zksync\libs\libzks-crypto.a it in my libs

gcc：gcc.exe (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders, r5) 13.2.0
go: go 1.21.1

**Comment by yanminmin** [comment]
The dll in windows system is missing
you can download from this url:
https://github.com/zksync-sdk/zksync-crypto-c/releases.

**Comment by babt123654** [comment]
> Windows 系统中缺少该 dll， 您可以从这个网址下载： https://github.com/zksync-sdk/zksync-crypto-c/releases。

![image](https://github.com/okx/go-wallet-sdk/assets/123553323/032e3c21-b720-45c8-8c86-d4ba984df7e7)
Excu sir, first of all thank you for your reply, but, I added this file to my libs directory and found it still does not work, can you help me to have a check? Looking forward to your reply!

**Comment by yanminmin** [comment]
Sorry ,I havent a windows computer.But you can try to change dll name to libzks-crypto.dll?it seems that golang cant find the dll file.
