### ISSUE TITLE
Update Tron.proto to the latest version

### ISSUE THREAD

**Issue by TheTeaParty** [okx/go-wallet-sdk#51]
this proto go file is heavily outdated, some methods are deprecated or missing like `FreezeBalanceV2`
https://github.com/okx/go-wallet-sdk/blob/main/coins/tron/pb/Tron.pb.go

I am going to update it

**Comment by leverwwz** [comment]
> this proto go file is heavily outdated, some methods are deprecated or missing like `FreezeBalanceV2` https://github.com/okx/go-wallet-sdk/blob/main/coins/tron/pb/Tron.pb.go
> 
> I am going to update it

thanks for your update
