### ISSUE TITLE
Solana decode raw transaction error

### ISSUE THREAD

**Issue by viaweb3** [okx/go-wallet-sdk#52]
When decode raw transaction that created by Dapp, it looks like the `accountTableLookups` field is lost.

Demo:
```golang
rawStr := `AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQADEO4Ti7ELpNlheK34aS1nU9SyOahrxNVhKc+HBUZ8Ok9+/r1cmarYUU2+uQ6Xfw2GeW+S3hbe7NhNes+gkeBjrDQGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAfWyieNQagqfYXHrGOZaCpVC7WHqfbyrZqba4MvDz3bR8M3vtrj9zOXD1v/fLYpG1Hu3oBu2o5UGbt1uv1R5/KDG+nrzvtutOj1l82qryXQxsbvkwtL24OR8pgIDRS9dYd6TBhiVE97EIUaTDBrSmxNiGFrvvaYVTVujoW1sUpU8W23FfY/TovEu0rqX0rE58cUzVl3A1cbBz//toyNr6uhssz2cjVCgS1WL7Q3b0kRCvws2k57E2iO7OUxnRHCpgzeZjMvy0EWLYVy8xrGjZ8R0np/vcwZiLhsbWJEBILyaUWe8Ce5CtE6sos2GtueIi2BEN2LGrxhcdoXf9Mkkob/ZbqMZ2O42JQfrfuwWxFdU4EE4tU9AOkF71ZDxKyf2ls2sAwhan+XTRRltrXJYuOBut94oEC91I0gF3n8u42ebAwZGb+UhFzL/7K26csOb57yM5bvF9xJrLEObOkAAAAAMwoDLa+MZLFA4OAHPRDAYD54/hmMiOsgBBpcQ2/fVB0FXsFgPMcX85EpiWC28+deO51lDoISjk7NQNo0iiZMIe0wTdioaHkfxqWFhqLW7pmeEA+i/4pO2PYD7PtMaZHIFDQAJA1z6DQAAAAAADQAFAtZyAgAOBgABAhAREgkFQEIPAAAAAAAOKRATERIAAQMUBAIFBg8GBgYHCAYGBgYGBhQDBQkKDwoKCgsMCgoKCgoKEQBAQg8AAAAAAAaKAQAAAAAADgYAAQAQERIBBgEZjx9MOkUiY9QTss0X68vBoOWIc2TmJhoSqBeS6hZaPgAFAgcAAw4=`
	tx := base.Transaction{}
	err := tx.UnmarshalBase64(rawStr)
	if err != nil {
		panic(err)
	}

	j, _ := json.Marshal(tx)
	println(string(j))
```
 This transaction is created by Raydium, when decode transaction by nodejs or `gagliardetto/solana-go`, it has `accountTableLookups`, when use `okx/go-wallet-sdk/`, it does not have `accountTableLookups`.

![image](https://github.com/okx/go-wallet-sdk/assets/17975348/8e4e4107-ac3d-4e9d-a3b8-081e107e1a2b)

**Comment by leverwwz** [comment]
> When decode raw transaction that created by Dapp, it looks like the `accountTableLookups` field is lost.
> 
> Demo:
> 
> ```go
> rawStr := `AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQADEO4Ti7ELpNlheK34aS1nU9SyOahrxNVhKc+HBUZ8Ok9+/r1cmarYUU2+uQ6Xfw2GeW+S3hbe7NhNes+gkeBjrDQGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAfWyieNQagqfYXHrGOZaCpVC7WHqfbyrZqba4MvDz3bR8M3vtrj9zOXD1v/fLYpG1Hu3oBu2o5UGbt1uv1R5/KDG+nrzvtutOj1l82qryXQxsbvkwtL24OR8pgIDRS9dYd6TBhiVE97EIUaTDBrSmxNiGFrvvaYVTVujoW1sUpU8W23FfY/TovEu0rqX0rE58cUzVl3A1cbBz//toyNr6uhssz2cjVCgS1WL7Q3b0kRCvws2k57E2iO7OUxnRHCpgzeZjMvy0EWLYVy8xrGjZ8R0np/vcwZiLhsbWJEBILyaUWe8Ce5CtE6sos2GtueIi2BEN2LGrxhcdoXf9Mkkob/ZbqMZ2O42JQfrfuwWxFdU4EE4tU9AOkF71ZDxKyf2ls2sAwhan+XTRRltrXJYuOBut94oEC91I0gF3n8u42ebAwZGb+UhFzL/7K26csOb57yM5bvF9xJrLEObOkAAAAAMwoDLa+MZLFA4OAHPRDAYD54/hmMiOsgBBpcQ2/fVB0FXsFgPMcX85EpiWC28+deO51lDoISjk7NQNo0iiZMIe0wTdioaHkfxqWFhqLW7pmeEA+i/4pO2PYD7PtMaZHIFDQAJA1z6DQAAAAAADQAFAtZyAgAOBgABAhAREgkFQEIPAAAAAAAOKRATERIAAQMUBAIFBg8GBgYHCAYGBgYGBhQDBQkKDwoKCgsMCgoKCgoKEQBAQg8AAAAAAAaKAQAAAAAADgYAAQAQERIBBgEZjx9MOkUiY9QTss0X68vBoOWIc2TmJhoSqBeS6hZaPgAFAgcAAw4=`
> 	tx := base.Transaction{}
> 	err := tx.UnmarshalBase64(rawStr)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	j, _ := json.Marshal(tx)
> 	println(string(j))
> ```
> 
> This transaction is created by Raydium, when decode transaction by nodejs or `gagliardetto/solana-go`, it has `accountTableLookups`, when use `okx/go-wallet-sdk/`, it does not have `accountTableLookups`.
> 
> ![image](https://private-user-images.githubusercontent.com/17975348/338839970-8e4e4107-ac3d-4e9d-a3b8-081e107e1a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzQ2NjAsIm5iZiI6MTcxODMzNDM2MCwicGF0aCI6Ii8xNzk3NTM0OC8zMzg4Mzk5NzAtOGU0ZTQxMDctYWMzZC00ZTlkLWEzYjgtMDgxZTEwN2UxYTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAzMDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMTQyZWE5ZjBhYTM4NzdkZGIwYzA3OGFiMTBiMmYxYjU5MGRlNDE0OTAxMWRjYzQ1ZmEyZjlmNGQ3ZTA4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d9Cd5JFSFXWUxqQXy24OcNERmuiABeFo125D2wMJ1A4)

==========================================
if you want to get the lookup table, please refer to this link, hope it work.

(https://docs.jup.ag/docs/additional-topics/composing-with-versioned-transaction)

**Comment by viaweb3** [comment]
https://github.com/viaweb3/go-wallet-sdk/commit/20e09eeeb262af69759de11cb69d1bd838b1eb6f
 @leverwwz
