### ISSUE TITLE
Return value error

### ISSUE THREAD

**Issue by albbm** [okx/go-wallet-sdk#54]
In the latest version of btcec/v2/ecdsa, SignCompact has removed the error return value and only returns a value

https://github.com/btcsuite/btcd/commit/e5d15fddb9c486dfe382bc95dc38d2fd247813bf

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/327571f4-04be-4265-9413-b3c9ea9077ad">

Source code needs to be modified
<img width="656" alt="image" src="https://github.com/user-attachments/assets/80df08f2-8db8-4170-9ef8-d1b00367d280">

**Comment by evieyee** [comment]
Thank you very much for pointing out this issue. The current code references a version of `btcsuite/btcd` that is not the latest. You can try modifying it to reference an earlier version. In the future, we will improve the `go.mod` file to make the build process easier.

**Comment by luyishisi** [comment]
Thank you for your attention to and use of the OKX open-source Go SDK. The error you encountered stems from your local environment not using the btcd version specified in the original go.mod file of the Git repository. Please revert to the specified version to eliminate this error.

As for the overall version upgrade of the dependencies in this repository, we will wait for the official stable release and comprehensively evaluate the necessity of the upgrade before proceeding.

Thank you again for your feedback.
