### ISSUE TITLE
Solana

### ISSUE THREAD

**Issue by marieclaudeguertin** [okx/go-wallet-sdk#69]
https://github.com/solana-labs/solana-program-library/blob/c3137af9dfa2cc0873cc84c4418dea88ac542965/token%2Fprogram-2022%2Finc%2Ftoken.h

**Comment by lucas7788** [comment]
> https://github.com/solana-labs/solana-program-library/blob/c3137af9dfa2cc0873cc84c4418dea88ac542965/token%2Fprogram-2022%2Finc%2Ftoken.h

go-sdk currently supports token2022. Could you please describe your problem in detail?

**Comment by luyishisi** [comment]
Since this question has not been updated for a long time, it is temporarily closed.
