### ISSUE TITLE
Bit

### ISSUE THREAD

**Issue by marieclaudeguertin** [okx/go-wallet-sdk#70]
> bc1qh23xljc8dgeux9vd7a5rsl6ye8e6xa5tvy6sj4 

 _Originally posted by @marieclaudeguertin in [046bf18](https://github.com/okx/go-wallet-sdk/commit/046bf1810b0a2edd5f1a1554eb9b6b2b8a7e484b#r148421627)_

**Comment by luyishisi** [comment]
Sorry, considering the security issues of SDK, this project does not support independent developers to participate in sharing. If you have optimization suggestions, we will make a comprehensive evaluation before moving forward.
