### ISSUE TITLE
Incompatibility with ecdsa.SignCompact return values

### ISSUE THREAD

**Issue by Shinku1014** [okx/go-wallet-sdk#71]
It seems that the ecdsa.SignCompact function in btcsuite has[ recently changed its implementation](https://github.com/btcsuite/btcd/blob/24eb815168f49dea84767817717a11bd7928eb23/btcec/ecdsa/signature.go#L235), which makes an incompatibility at okx/go-wallet-sdk/coins/bitcoin@v0.0.3/message.go:537:14:` sig, err := ecdsa.SignCompact(w.PrivKey, messageHash, true)`

Could we kindly request an update to the code to align with the new changes? Thank you for your attention to this matter.

**Comment by luyishisi** [comment]
When running this SDK, please use the specified dependent library version. We will make a comprehensive assessment before upgrading the latest version changes.

**Comment by Shinku1014** [comment]
> When running this SDK, please use the specified dependent library version. We will make a comprehensive assessment before upgrading the latest version changes.

Thank you for the guidance. I have resolved the issue following your advice.
