### ISSUE TITLE
tron 代码有问题: 依赖库的 SignCompact() 只有1个 返回值

### ISSUE THREAD

**Issue by kuchaguangjie** [okx/go-wallet-sdk#72]
![image](https://github.com/user-attachments/assets/de978ecc-f442-4587-921b-7bc39aa53200)

btcec 的 SignCompact() 只返回 1个值, tron.go 里 调用时 要了 2个值, 是不是 依赖版本有问题 导致的啊 !

![image](https://github.com/user-attachments/assets/e6a35c22-0112-4c37-a171-683617d91037)

**Comment by kuchaguangjie** [comment]
刚看到 别人已经 给了 PR 了: https://github.com/okx/go-wallet-sdk/pull/64
好几个 礼拜了, 还没 merge, 项目 黄了么 ?

**Comment by Shinku1014** [comment]
https://github.com/okx/go-wallet-sdk/issues/71
btcec 得 go get 手动设置一下用旧版本

**Comment by luyishisi** [comment]
感谢您的关注，此项目依旧在运营。
关于Pr，处于安全考虑，此项目暂不接受社区的代码pr。
关于问题，此升级系用户本地版本与项目需求版本不一致导致，建议修改本地版本行程一致即可解决。

**Comment by kuchaguangjie** [comment]
> 感谢您的关注，此项目依旧在运营。 关于Pr，处于安全考虑，此项目暂不接受社区的代码pr。 关于问题，此升级系用户本地版本与项目需求版本不一致导致，建议修改本地版本行程一致即可解决。

是你们自己代码版本有问题, 关用户毛事, 真垃圾.

**Comment by Shinku1014** [comment]
> > 感谢您的关注，此项目依旧在运营。 关于Pr，处于安全考虑，此项目暂不接受社区的代码pr。 关于问题，此升级系用户本地版本与项目需求版本不一致导致，建议修改本地版本行程一致即可解决。
> 
> 是你们自己代码版本有问题, 关用户毛事, 真垃圾.

硬要说起来其实是 btcec 缺德，小版本改接口格式，没法向后兼容

**Comment by kingsmao** [comment]
降低btcec版本可解决问题
`go get -u github.com/btcsuite/btcd/btcec/v2@v2.3.2  `
