### ISSUE TITLE
 Issue with Display of Decimal Token Approval Amounts in OKX Wallet

### ISSUE THREAD

**Issue by harissatti** [okx/go-wallet-sdk#8]
### Issue Description:
When utilizing the OKX Wallet for token approval within transactions on the Goerli test network, I encountered an issue related to the display of decimal token approval amounts. Here's a detailed description of the problem:

### Scenario: 
I attempted to approve fractional token amounts (e.g., 1.3, 6.8, 10.4) for transactions using the wallet's approval functionality.
**### Expected Behavior:** 
The wallet should accurately display the approved token amount, including both the whole number and fractional parts of the value.
### Actual Behavior: 
The wallet only displays the whole number portion of the decimal value (e.g., 1, 7, 11), omitting the fractional part.
This issue is specific to the token approval functionality within the wallet and arises only when approving tokens for another user via a smart contract. For instance, when dealing with decimal values like 1.1, the wallet displays the value as 1.

### Steps to Reproduce:

Open the OKX Wallet.
Navigate to the token approval section.
Attempt to approve fractional token amounts (e.g., 1.3, 6.8, 10.4) for transactions using smart contract.
Observe that the wallet displays only the whole number portion of the value.

### Expected Outcome:
The wallet should consistently display both whole numbers and decimal fractions in the approved token amounts for transactions, regardless of the input value.

Impact:
This issue disrupts the user experience when trying to approve fractional token amounts accurately for transactions. While there is a workaround involving manual customization, I believe the wallet's behavior should be consistent and intuitive, even when dealing with decimals.

**Comment by yanminmin** [comment]
done
